FROM python:3.9

# Stage 2: Working directory
WORKDIR /app/backend

# Copy requirements.txt
COPY backend/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY backend .

# Expose backend port
EXPOSE 8000

# Command to run the backend using uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]